// Car catalogue – each entry defines stats (1-10) and a "shape" used by the
// procedural CarModel builder.

export const PAINTS = [
  { name: "Cyber Red", hex: "#e11d48" },
  { name: "Electric Blue", hex: "#2563eb" },
  { name: "Neon Lime", hex: "#84cc16" },
  { name: "Sunset Orange", hex: "#f97316" },
  { name: "Arctic White", hex: "#f1f5f9" },
  { name: "Midnight Black", hex: "#111827" },
  { name: "Violet Storm", hex: "#8b5cf6" },
  { name: "Gold Rush", hex: "#eab308" },
  { name: "Teal Wave", hex: "#14b8a6" },
  { name: "Hot Pink", hex: "#ec4899" },
];

export const CARS = [
  {
    id: "sport",
    name: "Viper GT",
    category: "Sports Coupe",
    desc: "Balanced sports car. Sharp handling with punchy acceleration.",
    speed: 8,
    accel: 8,
    handling: 8,
    nitro: 7,
    shape: "sport",
    defaultPaint: "#e11d48",
    size: [2.0, 4.4],
  },
  {
    id: "hyper",
    name: "Phantom X",
    category: "Hypercar",
    desc: "Blistering top speed. A rocket on wheels for expert drivers.",
    speed: 10,
    accel: 9,
    handling: 7,
    nitro: 9,
    shape: "hyper",
    defaultPaint: "#f1f5f9",
    size: [2.1, 4.6],
  },
  {
    id: "muscle",
    name: "Thunder V8",
    category: "Muscle Car",
    desc: "Raw American power. Heavy but brutally fast in a straight line.",
    speed: 8,
    accel: 7,
    handling: 5,
    nitro: 9,
    shape: "muscle",
    defaultPaint: "#111827",
    size: [2.1, 4.8],
  },
  {
    id: "f1",
    name: "Apex F1",
    category: "Formula One",
    desc: "The pinnacle of racing. Unmatched grip and top speed, fragile body.",
    speed: 10,
    accel: 10,
    handling: 10,
    nitro: 8,
    shape: "f1",
    defaultPaint: "#2563eb",
    size: [2.0, 5.0],
  },
  {
    id: "rally",
    name: "Dust Devil",
    category: "Rally Car",
    desc: "Nimble and reactive. Loves quick lane changes.",
    speed: 7,
    accel: 8,
    handling: 10,
    nitro: 7,
    shape: "rally",
    defaultPaint: "#84cc16",
    size: [2.0, 4.3],
  },
  {
    id: "suv",
    name: "Ridgeback",
    category: "SUV",
    desc: "Tough and roomy. Takes more hits before going down.",
    speed: 6,
    accel: 6,
    handling: 6,
    nitro: 5,
    shape: "suv",
    defaultPaint: "#14b8a6",
    size: [2.2, 4.8],
    armor: 1.4,
  },
  {
    id: "pickup",
    name: "Hauler 4x4",
    category: "Pickup Truck",
    desc: "Workhorse with a big bed. Sturdy chassis and decent nitro.",
    speed: 6,
    accel: 5,
    handling: 5,
    nitro: 6,
    shape: "pickup",
    defaultPaint: "#f97316",
    size: [2.2, 5.4],
    armor: 1.4,
  },
  {
    id: "police",
    name: "Interceptor",
    category: "Police Cruiser",
    desc: "Pursuit-tuned sedan with flashing lights. Quick and stable.",
    speed: 8,
    accel: 8,
    handling: 8,
    nitro: 7,
    shape: "police",
    defaultPaint: "#f1f5f9",
    size: [2.0, 4.8],
  },
  {
    id: "taxi",
    name: "City Cab",
    category: "Taxi",
    desc: "Knows every shortcut. Modest speed, reliable handling.",
    speed: 6,
    accel: 6,
    handling: 7,
    nitro: 5,
    shape: "taxi",
    defaultPaint: "#eab308",
    size: [2.0, 4.6],
  },
  {
    id: "electric",
    name: "Volt S",
    category: "Electric Sedan",
    desc: "Instant torque. Silent, smooth and shockingly quick off the line.",
    speed: 9,
    accel: 10,
    handling: 8,
    nitro: 8,
    shape: "electric",
    defaultPaint: "#8b5cf6",
    size: [2.0, 4.8],
  },
  {
    id: "classic",
    name: "Retro 67",
    category: "Classic",
    desc: "Vintage charm with chrome bumpers. Cruise in style.",
    speed: 6,
    accel: 5,
    handling: 6,
    nitro: 5,
    shape: "classic",
    defaultPaint: "#ec4899",
    size: [2.0, 4.9],
  },
  {
    id: "monster",
    name: "Crusher XL",
    category: "Monster Truck",
    desc: "Gigantic wheels, absurd height. Shrugs off collisions.",
    speed: 5,
    accel: 5,
    handling: 4,
    nitro: 9,
    shape: "monster",
    defaultPaint: "#84cc16",
    size: [2.8, 5.2],
    armor: 2.0,
  },
  {
    id: "limo",
    name: "Royal Stretch",
    category: "Limousine",
    desc: "Incredibly long. Hard to steer, but oh so luxurious.",
    speed: 7,
    accel: 4,
    handling: 3,
    nitro: 4,
    shape: "limo",
    defaultPaint: "#111827",
    size: [2.0, 7.2],
  },
  {
    id: "van",
    name: "Cargo Max",
    category: "Delivery Van",
    desc: "Boxy and dependable. Deliveries wait for no one.",
    speed: 5,
    accel: 5,
    handling: 5,
    nitro: 4,
    shape: "van",
    defaultPaint: "#f1f5f9",
    size: [2.2, 5.4],
    armor: 1.3,
  },
  {
    id: "bus",
    name: "Metro Liner",
    category: "City Bus",
    desc: "Massive and heavy. Slow to steer but nearly indestructible.",
    speed: 4,
    accel: 3,
    handling: 3,
    nitro: 3,
    shape: "bus",
    defaultPaint: "#2563eb",
    size: [2.5, 10.0],
    armor: 2.2,
  },
  {
    id: "gokart",
    name: "Zippy Kart",
    category: "Go-Kart",
    desc: "Tiny and twitchy. Dodges anything but has no protection.",
    speed: 5,
    accel: 9,
    handling: 10,
    nitro: 6,
    shape: "gokart",
    defaultPaint: "#f97316",
    size: [1.4, 2.2],
    armor: 0.6,
  },
];

// Vehicles that appear as traffic on the highway (shapes + likely colours)
export const TRAFFIC_POOL = [
  "sport",
  "suv",
  "pickup",
  "taxi",
  "electric",
  "classic",
  "van",
  "bus",
  "muscle",
  "police",
  "limo",
  "rally",
];

export const TRAFFIC_COLORS = [
  "#94a3b8",
  "#f8fafc",
  "#1e293b",
  "#dc2626",
  "#2563eb",
  "#16a34a",
  "#facc15",
  "#f97316",
  "#a855f7",
  "#0ea5e9",
  "#78350f",
  "#e2e8f0",
];

export const getCar = (id) => CARS.find((c) => c.id === id) || CARS[0];
